### PR TITLE
case sensitive forms added

### PR DESCRIPTION
**Pull request by crystaltype**
@vv-monsalve

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@crystaltype please note that there is also a conflict in the PR. Please follow the instruction for the GitHub Desktop to solve them.

**Comment by crystaltype** [comment]
@googlebot I fixed it.

**Comment by crystaltype** [comment]
@googlebot I fixed it.

**Comment by vv-monsalve** [comment]
> @crystaltype please note that there is also a conflict in the PR. Please follow the instruction for the GitHub Desktop to solve them.

@crystaltype there is still a conflict to be solved this time about the files. Please follow the instructions for GitHub Desktop to solve it
Screen Shot 2021-04-15 at 17 55 19

**Comment by vv-monsalve** [comment]
Proces resumed in #6

**Pull request closed without merging**
